In [1]:
import numpy as np
import pandas as pd

movies = pd.read_csv('IMDb_movies.csv', dtype={'country': str, 'genre': str})
print(movies.shape)
movies.head()

(85855, 22)


D:\Data\A\Documents\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


imdb_title_id                        title               original_title  \
0     tt0000009                   Miss Jerry                   Miss Jerry   
1     tt0000574  The Story of the Kelly Gang  The Story of the Kelly Gang   
2     tt0001892               Den sorte drøm               Den sorte drøm   
3     tt0002101                    Cleopatra                    Cleopatra   
4     tt0002130                    L'Inferno                    L'Inferno   

   year date_published                      genre  duration           country  \
0  1894     1894-10-09                    Romance        45               USA   
1  1906     1906-12-26    Biography, Crime, Drama        70         Australia   
2  1911     1911-08-19                      Drama        53  Germany, Denmark   
3  1912     1912-11-13             Drama, History       100               USA   
4  1911     1911-03-06  Adventure, Drama, Fantasy        68             Italy   

  language                             director  ...  \
0     None                      Alexander Black  ...   
1     None                         Charles Tait  ...   
2      NaN                            Urban Gad  ...   
3  English                   Charles L. Gaskill  ...   
4  Italian  Francesco Bertolini, Adolfo Padovan  ...   

                                              actors  \
0  Blanche Bayliss, William Courtenay, Chauncey D...   
1  Elizabeth Tait, John Tait, Norman Campbell, Be...   
2  Asta Nielsen, Valdemar Psilander, Gunnar Helse...   
3  Helen Gardner, Pearl Sindelar, Miss Fielding, ...   
4  Salvatore Papa, Arturo Pirovano, Giuseppe de L...   

                                         description avg_vote votes   budget  \
0  The adventures of a female reporter in the 1890s.      5.9   154      NaN   
1  True story of notorious Australian outlaw Ned ...      6.1   589   $ 2250   
2  Two men of high rank are both wooing the beaut...      5.8   188      NaN   
3  The fabled queen of Egypt's affair with Roman ...      5.2   446  $ 45000   
4  Loosely adapted from Dante's Divine Comedy and...      7.0  2237      NaN   

   usa_gross_income worlwide_gross_income metascore reviews_from_users  \
0               NaN                   NaN       NaN                1.0   
1               NaN                   NaN       NaN                7.0   
2               NaN                   NaN       NaN                5.0   
3               NaN                   NaN       NaN               25.0   
4               NaN                   NaN       NaN               31.0   

   reviews_from_critics  
0                   2.0  
1                   7.0  
2                   2.0  
3                   3.0  
4                  14.0  

[5 rows x 22 columns]

In [2]:
movies.describe()

duration      avg_vote         votes     metascore  \
count  85855.000000  85855.000000  8.585500e+04  13305.000000   
mean     100.351418      5.898656  9.493490e+03     55.896881   
std       22.553848      1.234987  5.357436e+04     17.784874   
min       41.000000      1.000000  9.900000e+01      1.000000   
25%       88.000000      5.200000  2.050000e+02     43.000000   
50%       96.000000      6.100000  4.840000e+02     57.000000   
75%      108.000000      6.800000  1.766500e+03     69.000000   
max      808.000000      9.900000  2.278845e+06    100.000000   

       reviews_from_users  reviews_from_critics  
count        78258.000000          74058.000000  
mean            46.040826             27.479989  
std            178.511411             58.339158  
min              1.000000              1.000000  
25%              4.000000              3.000000  
50%              9.000000              8.000000  
75%             27.000000             23.000000  
max          10472.000000            999.000000

In [3]:
movies.dropna(subset=['genre','country','avg_vote','budget','usa_gross_income','worlwide_gross_income','metascore'], inplace=True)
movies.drop_duplicates(['title'], inplace=True)
movies = movies.drop(['title','original_title','date_published','duration','language','production_company','description','reviews_from_users','reviews_from_critics'], axis=1)
movies = movies.drop(['director','writer','actors'], axis=1)

In [4]:
print(movies.shape)
movies.head()


(6590, 10)


imdb_title_id  year                       genre  country  avg_vote  \
506      tt0017136  1927               Drama, Sci-Fi  Germany       8.3   
1048     tt0021749  1931      Comedy, Drama, Romance      USA       8.5   
2454     tt0027977  1936       Comedy, Drama, Family      USA       8.5   
2795     tt0029453  1937       Crime, Drama, Romance   France       7.7   
2827     tt0029583  1937  Animation, Family, Fantasy      USA       7.6   

       votes       budget usa_gross_income worlwide_gross_income  metascore  
506   156076  DEM 6000000        $ 1236166             $ 1349711       98.0  
1048  162668    $ 1500000          $ 19181               $ 46008       99.0  
2454  211250    $ 1500000         $ 163577              $ 457688       96.0  
2795    6180      $ 60000         $ 155895              $ 155895       98.0  
2827  177157    $ 1499000      $ 184925486           $ 184925486       95.0

In [5]:
movies['year'] = movies['year'].astype(int)
movies['avg_vote'] = movies['avg_vote'].astype(float)
movies['votes'] = movies['votes'].astype(int)

In [6]:
movies = movies[movies['year'] >= 1970]
movies.head()

imdb_title_id  year                         genre      country  \
4334      tt0035423  2001      Comedy, Fantasy, Romance          USA   
14260     tt0065134  1970       Adventure, Romance, War  USA, Mexico   
14323     tt0065377  1970       Action, Drama, Thriller          USA   
14340     tt0065421  1970  Animation, Adventure, Comedy          USA   
14357     tt0065462  1970     Action, Adventure, Sci-Fi          USA   

       avg_vote  votes      budget usa_gross_income worlwide_gross_income  \
4334        6.4  77852  $ 48000000       $ 47121859            $ 76019048   
14260       7.0  23223   $ 2500000        $ 5050000             $ 5050000   
14323       6.6  17068  $ 10000000      $ 100489151           $ 100489151   
14340       7.1  91085   $ 4000000       $ 35452658            $ 35459543   
14357       6.1  41159   $ 3000000       $ 18999718            $ 18999718   

       metascore  
4334        44.0  
14260       62.0  
14323       42.0  
14340       66.0  
14357       46.0

In [7]:
import re

movies.loc[:,'genre'] = movies.loc[:,'genre'].apply(lambda x: re.sub('[^a-zA-z0-9\s]','',x))
movies.loc[:,'country'] = movies.loc[:,'country'].apply(lambda x: re.sub('[^a-zA-z0-9\s]','',x))

movies.head()

imdb_title_id  year                       genre     country  avg_vote  \
4334      tt0035423  2001      Comedy Fantasy Romance         USA       6.4   
14260     tt0065134  1970       Adventure Romance War  USA Mexico       7.0   
14323     tt0065377  1970       Action Drama Thriller         USA       6.6   
14340     tt0065421  1970  Animation Adventure Comedy         USA       7.1   
14357     tt0065462  1970      Action Adventure SciFi         USA       6.1   

       votes      budget usa_gross_income worlwide_gross_income  metascore  
4334   77852  $ 48000000       $ 47121859            $ 76019048       44.0  
14260  23223   $ 2500000        $ 5050000             $ 5050000       62.0  
14323  17068  $ 10000000      $ 100489151           $ 100489151       42.0  
14340  91085   $ 4000000       $ 35452658            $ 35459543       66.0  
14357  41159   $ 3000000       $ 18999718            $ 18999718       46.0

In [8]:
def lower_case(input_str):
    input_str = input_str.lower()
    return input_str

movies.loc[:,'genre'] = movies.loc[:,'genre'].apply(lambda x: lower_case(x))
movies.loc[:,'country'] = movies.loc[:,'country'].apply(lambda x: lower_case(x))
movies.head()

imdb_title_id  year                       genre     country  avg_vote  \
4334      tt0035423  2001      comedy fantasy romance         usa       6.4   
14260     tt0065134  1970       adventure romance war  usa mexico       7.0   
14323     tt0065377  1970       action drama thriller         usa       6.6   
14340     tt0065421  1970  animation adventure comedy         usa       7.1   
14357     tt0065462  1970      action adventure scifi         usa       6.1   

       votes      budget usa_gross_income worlwide_gross_income  metascore  
4334   77852  $ 48000000       $ 47121859            $ 76019048       44.0  
14260  23223   $ 2500000        $ 5050000             $ 5050000       62.0  
14323  17068  $ 10000000      $ 100489151           $ 100489151       42.0  
14340  91085   $ 4000000       $ 35452658            $ 35459543       66.0  
14357  41159   $ 3000000       $ 18999718            $ 18999718       46.0

In [9]:
movies = movies.drop(['genre','country'], axis=1)

In [10]:
usd = movies[movies['budget'].str.contains("$")]
usd.loc[:,'budget'] = usd.loc[:,'budget'].apply(lambda x: re.sub('[^0-9\s]','',x))
usd.loc[:,'usa_gross_income'] = usd.loc[:,'usa_gross_income'].apply(lambda x: re.sub('[^0-9\s]','',x))
usd.loc[:,'worlwide_gross_income'] = usd.loc[:,'worlwide_gross_income'].apply(lambda x: re.sub('[^0-9\s]','',x))
print(usd.shape)
usd.head()

(6498, 8)


imdb_title_id  year  avg_vote  votes     budget usa_gross_income  \
4334      tt0035423  2001       6.4  77852   48000000         47121859   
14260     tt0065134  1970       7.0  23223    2500000          5050000   
14323     tt0065377  1970       6.6  17068   10000000        100489151   
14340     tt0065421  1970       7.1  91085    4000000         35452658   
14357     tt0065462  1970       6.1  41159    3000000         18999718   

      worlwide_gross_income  metascore  
4334               76019048       44.0  
14260               5050000       62.0  
14323             100489151       42.0  
14340              35459543       66.0  
14357              18999718       46.0

In [11]:
usd['budget'] = usd['budget'].astype(float)
usd['usa_gross_income'] = usd['usa_gross_income'].astype(float)
usd['worlwide_gross_income'] = usd['worlwide_gross_income'].astype(float)
usd.head()

imdb_title_id  year  avg_vote  votes      budget  usa_gross_income  \
4334      tt0035423  2001       6.4  77852  48000000.0        47121859.0   
14260     tt0065134  1970       7.0  23223   2500000.0         5050000.0   
14323     tt0065377  1970       6.6  17068  10000000.0       100489151.0   
14340     tt0065421  1970       7.1  91085   4000000.0        35452658.0   
14357     tt0065462  1970       6.1  41159   3000000.0        18999718.0   

       worlwide_gross_income  metascore  
4334              76019048.0       44.0  
14260              5050000.0       62.0  
14323            100489151.0       42.0  
14340             35459543.0       66.0  
14357             18999718.0       46.0

In [12]:
from sklearn.tree import DecisionTreeRegressor
import pydotplus #pip install pydotplus
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split

usd_train, usd_test = train_test_split(usd, test_size=0.2, random_state=42)

print("usd_train size:", len(usd_train))
print("usd_test size:", len(usd_test), "\n")

usd_train size: 5198
usd_test size: 1300 



In [13]:
usd_labels1 = usd_train['avg_vote']
usd_labels2 = usd_test['avg_vote']
print(usd_labels1.shape)
print(usd_labels2.shape)

(5198,)
(1300,)


In [14]:
usd_train = usd_train.drop(['avg_vote','imdb_title_id'], axis=1)
usd_test = usd_test.drop(['avg_vote','imdb_title_id'], axis=1)
usd_train.head()

year   votes       budget  usa_gross_income  worlwide_gross_income  \
43021  2004  351814  110000000.0       125544280.0           3.627443e+08   
59242  2011   31391    5000000.0            5043.0           4.453634e+06   
67523  2015  845102  245000000.0       936662225.0           2.068224e+09   
53018  2009   90686   60000000.0        43337279.0           6.235790e+07   
59809  2011  347242  125000000.0       209837675.0           6.261377e+08   

       metascore  
43021       58.0  
59242       37.0  
67523       80.0  
53018       34.0  
59809       66.0

In [15]:
usd_train.dtypes

year                       int32
votes                      int32
budget                   float64
usa_gross_income         float64
worlwide_gross_income    float64
metascore                float64
dtype: object

In [16]:
usd_train = usd_train.reset_index(drop = True)
usd_test = usd_test.reset_index(drop = True)
usd_labels1 = usd_labels1.reset_index(drop = True)
usd_labels2 = usd_labels2.reset_index(drop = True)

In [17]:
clf_tree = DecisionTreeRegressor()
clf_tree.fit(usd_train, usd_labels1)
pred = clf_tree.predict(usd_test)
print(pred)
print(usd_labels2)

[4.7 4.7 7.8 ... 6.8 7.3 7.3]
0       6.5
1       4.6
2       6.9
3       6.7
4       6.6
       ... 
1295    6.4
1296    7.5
1297    7.2
1298    7.4
1299    7.0
Name: avg_vote, Length: 1300, dtype: float64


In [18]:
conf = np.zeros(1300)
y = usd_labels2 - pred
y = abs(y)
y = y.reset_index(drop = True)

for i in range(1300):
    if y[i]<0.5 or y[i]==0.5:
        conf[i] = 1
        
print(y)
print(conf)
test = np.ones(1300)
print(test)

0       1.8
1       0.1
2       0.9
3       0.0
4       0.3
       ... 
1295    0.3
1296    1.8
1297    0.4
1298    0.1
1299    0.3
Name: avg_vote, Length: 1300, dtype: float64
[0. 1. 0. ... 1. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]


In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('Accuracy score: {}'.format(accuracy_score(conf,test)))
print('F1 score: {}'.format(f1_score(conf,test)))

Accuracy score: 0.5515384615384615
F1 score: 0.7109568666336142
